import test from 'node:test';
import assert from 'node:assert/strict';
import replay,{makeSession,readSession,validateRegistration,signedManifest} from '../api/replay.js';
import {RECORDINGS} from '../config/recordings.js';
process.env.SUPABASE_SERVICE_ROLE_KEY='synthetic-test-key-not-a-credential';
const id='11111111-1111-4111-8111-111111111111';
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(v){this.data=v;return this;},send(v){this.data=v;return this;}};}
const request=(query={},method='GET',body={})=>({query,method,body,headers:{origin:'https://www.risktakers.show'}});
test('sessions reject forged, expired and malformed tokens and contain no submitted PII',()=>{const token=makeSession(id,100000);assert.equal(readSession('rt_recordings='+token,101000).id,id);assert.equal(readSession('rt_recordings='+token,100000+31*86400000),null);assert.equal(readSession('rt_recordings='+token+'x',101000),null);assert.equal(readSession('rt_recordings=invalid'),null);assert.ok(!token.includes('@'));});
test('registration accepts bounded name/email only, normalizes email and rejects bot or invalid input',()=>{assert.deepEqual(validateRegistration({name:' Test Viewer ',email:'TEST@example.com'}),{name:'Test Viewer',email:'test@example.com'});for(const body of [{name:'X',email:'a@b.co'},{name:'Tester',email:'bad'},{name:'Tester',email:'a@b.co',website:'bot'},{name:'A'.repeat(121),email:'a@b.co'}])assert.throws(()=>validateRegistration(body));});
test('anonymous visitors cannot obtain stream URLs or manifest content',async()=>{const original=globalThis.fetch;globalThis.fetch=()=>{throw new Error('Unexpected backend call')};try{const r=response();await replay(request({action:'stream',id:'show'}),r);assert.equal(r.code,401);assert.ok(!JSON.stringify(r.data).includes('supabase'));assert.match(r.headers['Cache-Control'],/no-store/);}finally{globalThis.fetch=original;}});
test('cross-origin submissions cannot write leads or issue cookies',async()=>{const r=response();const req=request({action:'register'},'POST',{name:'Test Viewer',email:'test@example.com'});req.headers.origin='https://untrusted.example';await replay(req,r);assert.equal(r.code,403);assert.equal(r.headers['Set-Cookie'],undefined);});
test('a failed save never unlocks playback',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>new Response('database unavailable',{status:500});try{const r=response();await replay(request({action:'register'},'POST',{name:'Test Viewer',email:'test@example.com'}),r);assert.equal(r.code,503);assert.equal(r.headers['Set-Cookie'],undefined);}finally{globalThis.fetch=original;}});
test('saved registrations receive a secure HTTP-only cookie and no PII in response',async()=>{const original=globalThis.fetch;let saved;globalThis.fetch=async(url,options)=>{assert.match(url,/rpc\/register_recording_access$/);saved=JSON.parse(options.body);return Response.json(id);};try{const r=response();await replay(request({action:'register'},'POST',{name:'Test Viewer',email:'TEST@example.com'}),r);assert.equal(r.code,200);assert.equal(saved.p_email,'test@example.com');assert.match(r.headers['Set-Cookie'],/HttpOnly; Secure; SameSite=Lax/);assert.deepEqual(r.data,{unlocked:true});}finally{globalThis.fetch=original;}});
test('deleted or revoked registrations cannot reuse a still-signed session',async()=>{const original=globalThis.fetch;globalThis.fetch=async()=>Response.json([]);try{const req=request({action:'stream',id:'show'});req.headers.cookie='rt_recordings='+makeSession(id);const r=response();await replay(req,r);assert.equal(r.code,401);}finally{globalThis.fetch=original;}});
test('private HLS playlists sign the initialization file and every segment',async()=>{const original=globalThis.fetch;globalThis.fetch=async(url,opts)=>{if(!opts.method)return new Response('#EXTM3U\n#EXT-X-MAP:URI="init.mp4"\n#EXTINF:12,\nsegment-0000.m4s\n#EXT-X-ENDLIST\n');const body=JSON.parse(opts.body);assert.deepEqual(body.paths,['show/init.mp4','show/segment-0000.m4s']);assert.equal(body.expiresIn,7200);return Response.json(body.paths.map(path=>({path,signedURL:'/object/sign/private/'+path+'?token=synthetic'})));};try{const m=await signedManifest('show');assert.match(m,/#EXT-X-MAP:URI="https:\/\/umznkxyzovuzhavkmqjt.supabase.co\/storage\/v1\/object\/sign/);assert.equal((m.match(/token=synthetic/g)||[]).length,2);}finally{globalThis.fetch=original;}});
test('upload administration is disabled in production even with a matching key',async()=>{const prior=process.env.VERCEL_ENV;process.env.VERCEL_ENV='production';process.env.RECORDING_UPLOAD_KEY='synthetic-upload-test';try{const req=request({action:'upload'},'POST');req.headers.authorization='Bearer synthetic-upload-test';const r=response();await replay(req,r);assert.equal(r.code,404);}finally{process.env.VERCEL_ENV=prior||'';delete process.env.RECORDING_UPLOAD_KEY;}});
test('catalog contains one full episode and paired pitch/Q&A recordings for every vendor',()=>{assert.equal(RECORDINGS.length,11);assert.equal(RECORDINGS.filter(r=>r.kind==='episode').length,1);for(const vendor of ['terra','way','mine','tenet','act']){assert.ok(RECORDINGS.find(r=>r.id===vendor&&r.kind==='pitch'));assert.ok(RECORDINGS.find(r=>r.id===vendor+'-qa'&&r.kind==='qa'));}});

test('recording alerts are production-only, claimed once, escaped, and addressed only to Asaf',async()=>{
 const {notifyRegistration}=await import('../api/replay.js');const original=globalThis.fetch;const env=process.env.VERCEL_ENV;let pending=true,sends=0,updates=[];
 globalThis.fetch=async(url,options)=>{const body=JSON.parse(options.body);updates.push(body);if(url.includes('notification_status=eq.pending')){assert.match(url,/event_slug=eq.ai-defense-stack-showcase-day-n4qd/);const rows=pending?[{id,full_name:'<img src=x>',email:'viewer@example.com',created_at:'2026-09-24T06:00:00Z'}]:[];pending=false;return Response.json(rows);}return new Response(null,{status:204});};
 const deliver=async email=>{sends++;assert.equal(email.to,'asaf@risktakers.show');assert.equal(email.idempotencyKey,`recording-signup-${id}`);assert.ok(email.html.includes('&lt;img src=x&gt;'));assert.ok(!email.html.includes('<img src=x>'));assert.match(email.text,/viewer@example.com/);return {sent:true,id:'synthetic-provider-id'};};
 try{process.env.VERCEL_ENV='preview';await notifyRegistration(id,deliver);assert.equal(updates.length,0);process.env.VERCEL_ENV='production';await Promise.all([notifyRegistration(id,deliver),notifyRegistration(id,deliver)]);assert.equal(sends,1);assert.ok(updates.some(x=>x.notification_status==='sent'&&x.notification_provider_id==='synthetic-provider-id'));}finally{globalThis.fetch=original;process.env.VERCEL_ENV=env||'';}
});
test('notification rejection is persisted and registration access still succeeds on notification infrastructure failure',async()=>{
 const {notifyRegistration}=await import('../api/replay.js');const original=globalThis.fetch,env=process.env.VERCEL_ENV,log=console.error;const updates=[];console.error=()=>{};process.env.VERCEL_ENV='production';
 try{globalThis.fetch=async(url,options)=>{updates.push(JSON.parse(options.body));return url.includes('notification_status=eq.pending')?Response.json([{id,full_name:'Test Viewer',email:'test@example.com',created_at:'2026-09-24'}]):new Response(null,{status:204});};await notifyRegistration(id,async()=>({sent:false,error:{code:'provider_rejected'}}));assert.ok(updates.some(x=>x.notification_status==='failed'&&x.notification_sent_at===null));globalThis.fetch=async url=>url.endsWith('/rpc/register_recording_access')?Response.json(id):new Response('unavailable',{status:500});const r=response();await replay(request({action:'register'},'POST',{name:'Test Viewer',email:'test@example.com'}),r);assert.equal(r.code,200);assert.deepEqual(r.data,{unlocked:true});assert.match(r.headers['Set-Cookie'],/HttpOnly/);}finally{globalThis.fetch=original;process.env.VERCEL_ENV=env||'';console.error=log;}
});
