export const merchProducts = [
  {
    id: 'human-in-the-loop-tee',
    name: 'Human in the Loop Tee',
    shortName: 'Human in the Loop Tee',
    category: 'Heavyweight tee',
    retailValue: 39,
    description: 'A washed-black heavyweight tee for the person still accountable when the model stops talking.',
    details: ['Heavyweight cotton concept', 'Relaxed unisex fit', 'Washed black'],
    image: '/merch/mockups/tee-human-in-the-loop-v2.png',
  },
  {
    id: 'zero-trust-high-agency-hoodie',
    name: 'High Agency Hoodie',
    shortName: 'High Agency Hoodie',
    category: 'Premium hoodie',
    retailValue: 79,
    description: 'A clean heavyweight layer built around one operating principle: zero trust, high agency.',
    details: ['Heavyweight fleece concept', 'Relaxed unisex fit', 'Washed black'],
    image: '/merch/mockups/hoodie-zero-trust-high-agency-v2.png',
  },
  {
    id: 'prompt-injection-fuel-mug',
    name: 'Operator Fuel Mug',
    shortName: 'Operator Fuel Mug',
    category: 'Ceramic mug',
    retailValue: 28,
    description: 'Matte ceramic, restrained branding, and enough capacity for the decisions that cannot be delegated.',
    details: ['Matte ceramic concept', '11 oz format', 'Charcoal finish'],
    image: '/merch/mockups/mug-prompt-injection-fuel-v2.png',
  },
  {
    id: 'attack-surface-desk-mat',
    name: 'Attack Surface Desk Mat',
    shortName: 'Attack Surface Mat',
    category: 'Extended desk mat',
    retailValue: 49,
    description: 'A low-noise extended desk surface for mapping the problem before making the move.',
    details: ['31.5 × 15.5 in concept', '3 mm neoprene', 'Low-profile edge'],
    image: '/merch/mockups/deskmat-attack-surface-v2.png',
  },
  {
    id: 'risk-takers-logo-sticker',
    name: 'Risk Takers Vinyl Mark',
    shortName: 'Vinyl Mark',
    category: 'Kiss-cut sticker',
    retailValue: 8,
    description: 'The original Risk Takers mark as a durable, matte piece for the hardware that follows you.',
    details: ['Matte vinyl concept', 'Die-cut finish', '3 × 3 in'],
    image: '/merch/mockups/sticker-risk-takers-v2.png',
  },
  {
    id: 'operators-desk-kit',
    name: 'Operator Desk Set',
    shortName: 'Operator Desk Set',
    category: 'Two-piece set',
    retailValue: 77,
    description: 'The desk mat and ceramic mug paired as a useful, high-value gift for the operator in the room.',
    details: ['Two-piece concept', 'Mug + desk mat', 'Gift-ready direction'],
    image: '/merch/hero/risk-takers-merch-real-v2.png',
  },
];

export const formatMerchPrice = (value) =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(value);
