export const merchProducts = [
  {
    id: 'human-in-the-loop-tee',
    name: 'Human in the Loop Tee',
    shortName: 'Control Layer Tee',
    category: 'Heavyweight tee',
    retailValue: 39,
    description: 'A reminder that the best AI system still needs judgment at the edge.',
    details: ['Garment-dyed heavyweight cotton', 'Unisex fit', 'Black / S–4XL'],
    image: '/merch/mockups/tee-human-in-the-loop.jpg',
    badge: 'DROP 001',
  },
  {
    id: 'zero-trust-high-agency-hoodie',
    name: 'Zero Trust / High Agency Hoodie',
    shortName: 'High Agency Hoodie',
    category: 'Premium hoodie',
    retailValue: 79,
    description: 'Verify the system. Trust the operator. Built for people who own the outcome.',
    details: ['Premium midweight fleece', 'Unisex fit', 'Black / S–3XL'],
    image: '/merch/mockups/hoodie-zero-trust-high-agency.jpg',
    badge: 'SIGNATURE',
  },
  {
    id: 'prompt-injection-fuel-mug',
    name: 'Prompt Injection Fuel Mug',
    shortName: 'Prompt Fuel Mug',
    category: 'Ceramic mug',
    retailValue: 28,
    description: 'Caffeine is useful. An authentication boundary it is not.',
    details: ['Ceramic', 'Dishwasher safe', '11 oz / black interior'],
    image: '/merch/mockups/mug-prompt-injection-fuel.jpg',
    badge: 'OPERATOR FUEL',
  },
  {
    id: 'attack-surface-desk-mat',
    name: 'Attack Surface Desk Mat',
    shortName: 'Attack Surface Mat',
    category: 'Extended desk mat',
    retailValue: 49,
    description: 'Map the surface. Make the move. Verify everything before you ship.',
    details: ['31.5 × 15.5 in', '3 mm neoprene', 'Anti-slip backing'],
    image: '/merch/mockups/deskmat-attack-surface.jpg',
    badge: 'BEST GIFT VALUE',
  },
  {
    id: 'risk-takers-logo-sticker',
    name: 'Risk Takers Logo Sticker',
    shortName: 'Logo Sticker',
    category: 'Kiss-cut sticker',
    retailValue: 8,
    description: 'The original Risk Takers mark, scaled for the gear that follows you everywhere.',
    details: ['Durable indoor vinyl', 'Kiss-cut finish', '3 × 3 in'],
    image: '/merch/mockups/sticker-take-the-risk.jpg',
    badge: 'ADD-ON',
  },
  {
    id: 'operators-desk-kit',
    name: "Operator's Desk Kit",
    shortName: 'Desk Kit',
    category: 'Retail bundle',
    retailValue: 77,
    description: 'The Attack Surface desk mat and Prompt Injection Fuel mug in one high-value operator set.',
    details: ['Two-piece concept', 'Mug + desk mat', 'Designed as one gift'],
    image: '/merch/hero/risk-takers-gift-store-hero.png',
    badge: 'BUNDLE VALUE',
  },
];

export const formatMerchPrice = (value) =>
  new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(value);
